### ISSUE TITLE
Is there way to get Ru-Ru dictionary that

### ISSUE THREAD

**Issue by 7enet** [Vuizur/ebook_dictionary_creator#6]
you shared in here, in .mobi version: https://github.com/Vuizur/add-stress-to-epub

Because I tried almost everything I am capable of but couldn't manage to convert to mobi. Is it possible, if so, can you help me? I tried to use it on mobile and it works great for me and I want to use on Kindle as well. 

Thank you.

**Comment by Vuizur** [comment]
I used Pyglossary to convert it, the (untested) result is here: https://github.com/Vuizur/ebook_dictionary_creator/releases/download/v1.0.0/ru_ru_dictionary.zip

No idea how well it works.

**Comment by 7enet** [comment]
Works great, thank you so much for your hard work.

**Comment by Vuizur** [comment]
You're welcome!
